"use client";

const SERVER = process.env.NEXT_PUBLIC_SERVER;
const NEXT_SERVER = process.env.NEXT_PUBLIC_NEXT_SERVER;
const CK_EDITOR_LICENSE_KEY = process.env.NEXT_PUBLIC_CKEDITOR_LICENSE_KEY;

export { SERVER, NEXT_SERVER, CK_EDITOR_LICENSE_KEY };